server:
  port: 8080
spring:
  application:
    name: oracle-mcp-server
  ai:
    mcp:
      server:
        enabled: true
oracle:
  connection-string: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
  username: OCI_PLATFORM
  password: OCI_PLATFORM
